name: Log

on:
  repository_dispatch:
    types: [fmvilas/test-repo-1/release]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: |
          echo "${{toJson(github.event)}}"